/**
 * © 2015 Cedexis Inc.
 * Radar JavaScript client
 * Application Version: 0.1.230
 * Build Timestamp: 1444163736
 */
(function(window,document){'use strict';function m(d){var h=d.Ra||18,g=d.Sa||18,b,e,k,l;this.g=d.w;this.T=d.samplerId;this.F=[];this.g.cedexis=this.g.cedexis||{};this.g.cedexis.callbacks=this.g.cedexis.callbacks||[];this.ua=function(){return b};this.va=function(){return document};this.na=function(a,c){for(var f=[],b=0;100>b&&(0<a.length||0<c.length);)0<a.length&&f.push(a.shift()),0<c.length&&f.push(c.shift()),b+=1;return f};this.C=function(){return(new Date).getTime()};this.j=function(a,c){return setTimeout(a,c)};this.k=function(a){clearTimeout(a)};
this.y64enc=this.M=function(){return function(a){var c="",f,b,e,d,g,h,k=0;a=a.replace(/\r\n/g,"\n");b="";for(e=0;e<a.length;e+=1)d=a.charCodeAt(e),128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128));for(a=b;k<a.length;)f=a.charCodeAt(k),k+=1,b=a.charCodeAt(k),k+=1,e=a.charCodeAt(k),k+=1,d=f>>2,f=(f&3)<<4|b>>4,g=(b&15)<<2|e>>6,h=e&63,isNaN(b)?g=h=64:isNaN(e)&&(h=64),
c=c+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(f)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(h);return c}}();this.Y=function(a){var c=/radar_(tags|impact)_(\w{3,})/i,f;if(("radar_tags_"===a.slice(0,11)||"radar_impact_"===a.slice(0,13))&&(c=c.exec(a))&&3===c.length){try{f=p(window[a])}catch(b){return null}return c[2]+
":"+this.M(f)}return null};this.v=function(a){if(!a.includePartnerTags)return"0";if(!window.JSON||"function"!==typeof window.JSON.stringify)return"1";if(a=a.getImpactObject()){var c;try{c=p(a)}catch(f){return"error"}try{c=this.M(c)}catch(b){return"error"}return"impact_kpi:"+c}c=[];for(var e in window){a=null;if(void 0!==window.hasOwnProperty)window.hasOwnProperty(e)&&(a=this.Y(e));else try{void 0!==window[e]&&(a=this.Y(e))}catch(d){}a&&c.push(a)}return 1>c.length?"0":c.join("@")};this.B=function(a){var c=
document.getElementById("cdx");c||(c=document.createElement("div"),c.id="cdx",document.body.appendChild(c));c.appendChild(a)};this.Z=function(){return Math.random()};this.xa=function(a){return Math.floor(this.Z()*(a-0+1))+0};this.I=function(a,c){var f,b=[];c=c||"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";for(f=0;f<a;f+=1)b.push(c.charAt(this.xa(c.length-1)));return b.join("")};this.ka=function(a){return/http:/i.test(a)?"http":/https:/i.test(a)?"https":/\/\//.test(a)?window.location.protocol.replace(":",
""):null};this.ia=function(){var a=[],c=b.p.p,f,e;c.a&&c.a.a?a.push({a:"cold",b:1,f:!!c.d,t:c.a.a.t,u:c.a.a.u}):c.b&&c.b.a&&a.push({a:"cold",b:1,f:!!c.d,t:c.b.a.t,u:c.b.a.u});c.d&&a.push({a:"uni",t:c.d.t,u:c.d.u});if(c.a)for(c.a.b&&a.push({a:"rtt",b:0,f:!!c.d,t:c.a.b.t,u:c.a.b.u}),e=b.b,f=0;f<e;f++)c.a.c&&a.push({a:"kbps",b:14,f:!!c.d,t:c.a.c.t,u:c.a.c.u,report:e-1===f,probeIdSuffix:0===f?"":String.fromCharCode(97+f)});else if(c.b)for(c.b.b&&a.push({a:"rtt",b:0,f:!!c.d,t:c.b.b.t,u:c.b.b.u}),e=b.b,
f=0;f<e;f++)c.b.c&&a.push({a:"kbps",b:14,f:!!c.d,t:c.b.c.t,u:c.b.c.u,report:e-1===f,probeIdSuffix:0===f?"":String.fromCharCode(97+f)});c.c&&(f=this.ka(c.c.u))&&("http:"!==this.g.location.protocol&&"https"!==f||a.push({a:"custom",b:2,f:!!c.d,t:c.c.t,u:c.c.u}));b.H=a};this.ja=function(a){var c=[];a.connect&&c.push({a:"cold",b:1,f:!1,t:1,u:a.connect});a.response_time&&c.push({a:"rtt",b:0,f:!1,t:1,u:a.response_time});a.kbps&&c.push({a:"kbps",b:14,f:!1,t:1,u:a.kbps});b.H=c};this.Ka=function(a){return"uni"===
a?[b.requestor.zoneId,b.requestor.customerId,b.p.z,b.p.c,b.p.i,this.I(8),b.requestor.requestSignature].join("-"):[a,b.requestor.zoneId,b.requestor.customerId,b.p.z,b.p.c,b.p.i,b.requestor.transactionId,b.requestor.requestSignature].join("-")};this.n=function(a,c){var f="";a=a||e.u;if(!1!==b.a){f="?rnd=";-1<a.indexOf("?",0)&&(f="&rnd=");var d;"uni"===e.a?d="uni":d=e.b+(c||"");f+=this.Ka(d)}return a+f};this.Ba=function(a){var c=a.indexOf("//");if(-1<c){var f=a.substring(c+2),b="//";0<c&&(b=a.substring(0,
c)+"//");a=f.split("/");a[0]=this.I(63,"abcdefghijklmnopqrstuvwxyz")+"."+a[0];return b+a.join("/")}return null};this.V=function(a,c){var f=/(\d+)kb\./i.exec(c);return!f||2>f.length?0:Math.floor(8E3*parseInt(f[1],10)/a)};this.G=function(a){var c,f,d;if(b&&e){b.c?(c=b.c.a,f=b.c.b,d=b.c.c):(c=b.p.z,f=b.p.c,d=b.p.i);q(this,"sendSuccessReport",{providerOwnerZoneId:c,providerOwnerCustomerId:f,providerId:d,probeId:e.b,resultCode:0,value:a});var g=b.requestor;a=[g.domains.report,"f1",g.requestSignature,c,
f,d,e.b,0,a,k||"0",this.v(g)];this.q("//"+a.join("/"));this.j(this.J(),200)}};this.J=function(){var a=this;return function(){a.h()}};this.Fa=function(){var a=this;return function(){a.o()}};this.l=function(a){var c,f,d;if(b&&e){b.c?(c=b.c.a,f=b.c.b,d=b.c.c):(c=b.p.z,f=b.p.c,d=b.p.i);q(this,"sendErrorReport",{providerOwnerZoneId:c,providerOwnerCustomerId:f,providerId:d,probeId:e.b,resultCode:a,value:0});var g=b.requestor;a=[g.domains.report,"f1",g.requestSignature,c,f,d,e.b,a,0,k||"0",this.v(g)];this.q("//"+
a.join("/"));this.j(this.Fa(),200)}};this.L=function(a){return!0===a.f&&null===k};this.W=function(a,c,f){a===e&&(c=f.call(null,c),0<c&&4E3>=c?(f=c,14===a.b&&(f=this.V(c,a.u)),this.L(a)?(l={probe:a,measurement:f},this.h()):this.G(f)):this.l(1))};this.Ma=function(a,c,f){var b=this;return function(){a.c||(b.k(a.e),b.W(a,c,f))}};this.K=function(a){var c,f;c=document.createElement("script");c.async=!0;c.src=this.n();e.c=!1;e.d="loading";f=this.C();void 0!==c.onreadystatechange?c.onreadystatechange=function(c,
b){var d=!1;return function(){d||"loaded"!==this.readyState&&"complete"!==this.readyState||(d=!0,b!==e||b.c||(c.k(b.e),c.W(b,f,a)))}}(this,e):c.onload=this.Ma(e,f,a);c.onerror=function(a,c){return function(){c===e&&(a.k(c.e),c.c=!0,c.d="error",a.l(4))}}(this,e);e.e=this.j(this.A(),4E3);window.radar.stoppedAt=window.cedexis.radar.stopped_at=null;this.B(c)};this.aa=function(){var a=this;return function(c){return a.C()-c}};this.A=function(a){var c=this,b=e;return function(){var d=1;b.c||(a&&a.call(null),
b===e&&("loaded"===b.d&&(d=4),b.c=!0,b.d="timeout",c.l(d)))}};this.Aa=function(){var a=this;return function(){k="2";a.D()}};this.Da=function(){var a=this,c=e,b;return b=function(){a.k(c.e);this.removeEventListener("load",b,!1);c.c||(c.d="loaded")}};this.Ea=function(a,c){return function(){a.removeEventListener("load",c,!1)}};this.Ca=function(){var a=this,c=e,f;return f=function(d){if(c===e){var g;try{g=JSON.parse(d.data)}catch(h){}if(g&&g.source&&"dsa"===g.source&&"l"!==g.s&&"s"===g.s){if(!c.c){d=
g.m.responseEnd-g.m.domainLookupStart;var u=b.requestor,n=[u.domains.report,"f1",u.requestSignature,g.p.z,g.p.c,g.p.i,g.m.probe_id],v=0;if(4E3>=d){if(a.L(c)){l={probe:c,measurement:d,extraFields:[g.m.ciphertext]};a.h();return}}else v=1,d=0;n.push(v);n.push(d);q(a,"sendDsaReport",{providerOwnerZoneId:g.p.z,providerOwnerCustomerId:g.p.c,providerId:g.p.i,probeId:g.m.probe_id,resultCode:v,value:d});n.push(k||"0");n.push(a.v(u));n.push(g.m.ciphertext);a.q("//"+n.join("/"));a.j(a.J(),200)}window.removeEventListener("message",
f,!1)}}}};this.da=function(){var a=document.createElement("iframe"),c=this.n(),b=this.Da();window.addEventListener("message",this.Ca(),!1);a.addEventListener("load",b,!1);a.src=c;a.style.display="none";e.c=!1;e.d="loading";e.e=this.j(this.A(this.Ea(a,b)),4E3);this.B(a)};this.fa=function(){this.K(function(a){return window.radar.stoppedAt?window.radar.stoppedAt.getTime()-a:window.cedexis.radar.stopped_at?window.cedexis.radar.stopped_at.getTime()-a:null})};this.Ga=function(a,c){var b=this;return function(){b.k(a.e);
b.G(b.C()-c)}};this.ca=function(){var a=this.va().createElement("iframe"),c=this.C();a.src=this.n();a.style.display="none";e.c=!1;e.d="loading";a.onload=this.Ga(e,c);e.e=this.j(this.A(),4E3);this.B(a)};this.X=function(a){if(this.g.performance&&this.g.performance.getEntriesByType)for(var c=this.g.performance.getEntriesByType("resource"),b=c.length;b--;)if(c[b].name===a)return c[b];return null};this.Ha=function(a){var c=this;return function(){c.k(a.e);if(!a.c)if("report"in a&&!a.report)c.h();else{var b=
c.X(this.src);if(b){var d=14===a.b,b=0<b.requestStart?d?Math.round(b.responseEnd-b.requestStart):Math.round(b.responseStart-b.requestStart):Math.round(b.duration);if(1>b)c.o();else if(0<b&&4E3>=b){var e=b;d&&(e=c.V(b,a.u));c.L(a)?(l={probe:a,measurement:e},c.h()):c.G(e)}else c.l(1)}}}};this.Ia=function(a){var c=this;return function(){c.k(a.e);if(!a.c){var b=c.X(this.src);b&&(b=0<b.requestStart?Math.round(b.domainLookupEnd-b.domainLookupStart):Math.round(b.duration),1>b?c.o():4E3>=b?c.G(b):c.l(1))}}};
this.ba=function(a){var b=this;return function(){b.k(a.e);a.c=!0;a.d="error";b.l(4)}};this.ea=function(){if("performance"in this.g&&"getEntriesByType"in this.g.performance){var a=new Image;a.onload=this.Ha(e);a.onerror=this.ba(e);e.c=!1;e.d="loading";e.e=this.j(this.A(),4E3);a.src=this.n(void 0,e.probeIdSuffix||null)}else this.h()};this.ha=function(){var a=new Image;a.onload=this.Ia(e);a.onerror=this.ba(e);e.c=!1;e.d="loading";e.e=this.j(this.A(),4E3);var b=this.Ba(e.u);b?a.src=this.n(b):this.h()};
this.D=function(){if(l){var a=b.requestor,a=[a.domains.report,"f1",a.requestSignature,b.p.z,b.p.c,b.p.i,l.probe.b,0,l.measurement,k||"0",this.v(a)];if("extraFields"in l)for(var c=0;c<l.extraFields.length;c+=1)a.push(l.extraFields[c]);this.q("//"+a.join("/"));this.j(this.J(),200)}else this.h()};this.Oa=function(a){var c=this;return function(f){e!==a||b.p.i!==f.id||a.c||(a.d="loaded",k=f.node,c.D())}};this.Qa=function(){return function(){}};this.Pa=function(){return function(){}};this.qa=function(){var a,
b;a=document.createElement("script");b=this.n();window.cdx=window.cdx||{};window.cdx.s=window.cdx.s||{};window.cdx.s.b=this.Oa(e);a.onload=this.Qa();a.onerror=this.Pa();e.c=!1;e.d="loading";a.type="text/javascript";a.async=!0;a.src=b;this.B(a)};this.Na=function(){var a=this;return function(c){var f,d,g;if(b&&e){try{f=JSON.parse(c.data)}catch(h){}f&&"uni"===f.source&&(c=parseInt(f.p.z,10),d=parseInt(f.p.c,10),g=parseInt(f.p.i,10),g===b.p.i&&d===b.p.c&&c===b.p.z&&f.r.z===b.requestor.zoneId&&f.r.c===
b.requestor.customerId&&(a.k(e.e),"l"===f.s?e.d="loaded":-1<"es".indexOf(f.s)&&("e"===f.s?(e.d="error",k="2"):"s"===f.s&&(k=f.node_id),a.D())))}}};this.ra=function(){return"function"===typeof window.postMessage&&"function"===typeof window.addEventListener};this.pa=function(){var a;this.ra()?(e.c=!1,e.d="loading",a=document.createElement("iframe"),a.style.display="none",a.src=this.n(),e.e=this.j(this.Aa(),4E3),this.B(a)):(k="1",this.D())};this.wa=function(a){a=a.slice(a.lastIndexOf("/")+1);var b=[/cdx10b/,
/rdr12/,/radar\.js/,/r\d+(-\d+kb)?\.js/i,/r\d+\w+(-\d+kb)?\.js/i],f;if("d17.html"===a)return 4;for(f=0;f<b.length;f+=1)if(b[f].test(a))return 1;return/\.js(\?)?/i.test(a)?5:/\.(ico|png|bmp|gif|jpg|jpeg)(\?)?/i.test(a)?2:/\.(htm(l)?)(\?)?/i.test(a)?3:null};this.oa=function(){var a;if(e)switch(e.t){case 1:this.fa();break;case 2:this.ea();break;case 3:this.ca();break;case 4:this.da();break;case 5:this.K(this.aa());break;case 6:a=this.wa(e.u);switch(a){case 1:this.fa();break;case 2:this.ea();break;case 3:this.ca();
break;case 4:this.da();break;case 5:this.K(this.aa());break;default:this.l(5)}break;case 7:this.pa();break;case 8:this.qa();break;case 9:this.ha();break;default:this.l(6)}};this.h=function(){b&&(0<b.H.length?(e=b.H.shift(),this.oa()):(b=null,this.o()))};this.o=function(){b=e=null;0<this.F.length?(l=k=null,b=this.F.shift(),q(this,"measureProvider",{providerOwnerZoneId:b.p.z,providerOwnerCustomerId:b.p.c,providerId:b.p.i}),b.p.source_url?this.la():(this.ia(),this.h())):q(this,"radarSessionFinished")};
this.la=function(){var a,c,f;window.XMLHttpRequest&&(c=new window.XMLHttpRequest)&&(a=b.p.source_url,f=Math.ceil(99999999*this.Z()),a=0>a.indexOf("?",0)?a+("?rnd="+f):a+("&rnd="+f),c.open("GET",a,!0),c.onreadystatechange=this.La(),c.send())};this.La=function(){var a=this,c=b;return function(){var f;200===this.status&&4===this.readyState&&(f=JSON.parse(this.responseText),c===b&&(a.ja(f),0<b.H.length?a.h():a.o()))}};this.ya=function(){var a=0;window.chrome&&window.chrome.loadTimes?(a=window.chrome.loadTimes(),
a=Math.round(1E3*a.firstPaintTime)):window.performance&&window.performance.timing&&window.performance.timing.msFirstPaint&&(a=Math.round(window.performance.timing.msFirstPaint));return a};this.Ja=function(a){return this.$(a,a.transactionId)};this.$=function(a,b){if(this.g.location&&this.g.location.protocol){var f="https:"===this.g.location.protocol?"s":"i",d=[];d.push("i1");d.push(this.T);d.push(h);d.push(g);d.push(a.zoneId);d.push(a.customerId);d.push(b.toString(10));d.push(f);d=d.join("-");f=[];
f.push(d+".init."+a.domains.init);f.push("i1");f.push(Math.floor((new Date).getTime()/1E3).toString(10));f.push(b.toString(10));f.push("xml");f="//"+f.join("/");return f+("?seed="+d)}return""};this.za=function(a,b){for(var d=0;d<a.length;d+=1)a[d].requestor=b;this.F=this.na(this.F,a);this.ua()||this.o()};this.run=this.ma=function(a){a.runCalledAt=(new Date).getTime();var b=this.g.performance;if(b){var d=b.setResourceTimingBufferSize||b.webkitSetResourceTimingBufferSize;d&&d.call(b,300)}r({a:this.Ja(a),
b:t(this,a)});"afterRun"in a&&a.afterRun()};"function"===typeof window.addEventListener&&window.addEventListener("message",this.Na(),!1)}m.prototype.ga="navigationStart unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" ");
function q(d,h,g){for(var b=d.g.cedexis,e=b.callbacks,k=e.length;k--;)"function"===typeof e[k]&&e[k].call(d.g,h,g);for(var l in b.requestors)b.requestors.hasOwnProperty(l)&&b.requestors[l].sendParentMessages&&d.g.parent&&"function"===typeof d.g.parent.postMessage&&d.g.parent.postMessage({radar:{type:"status",data:{messageName:h,messageData:g}}},"*")}m.prototype.log=function(d){var h=this.g.console;h&&h.log&&h.log.call(h,(new Date).toUTCString()+": "+d)};
m.prototype.ta=function(){if(this.g.performance&&this.g.performance.getEntriesByType){for(var d=this.g.performance.getEntriesByType("resource"),h=d.length,g={},b;h--;){var e=d[h];b=e.name.split("//");if(b[1]){b=b[1].split("/");b=g[b[0]]=g[b[0]]||{R:0,S:0,N:0,O:0};var k,l;0<e.requestStart?(l=Math.round(e.responseEnd-e.requestStart),k=Math.round(e.responseStart-e.requestStart)):k=l=Math.round(e.duration);9<k&&(b.R+=k,b.N+=1);9<l&&(b.S+=l,b.O+=1);k=Math.round(e.startTime);b.Q="undefined"===typeof b.Q?
k:Math.min(k,b.Q);k=Math.round(e.responseEnd);b.P="undefined"===typeof b.P?k:Math.max(k,b.P)}}var d=[],a;for(a in g)g.hasOwnProperty(a)&&(b=g[a],d.push([a,b.R,b.S,b.N,b.Q,b.P,b.O]));return d}return null};m.prototype.getDomainPerformance=m.prototype.ta;
function w(d,h){var g=(d.g.performance||{}).timing;if(g){if(0===g.loadEventEnd){d.U=d.g.setInterval(x(d,h),1E3);return}for(var b=[h.domains.report,"n1",0],e=0;e<d.ga.length;e+=1){var k=g[d.ga[e]];b.push(void 0===k?0:k)}b.push(h.requestSignature);b.push(d.v(h));b.push(d.ya());g.connectEnd<g.connectStart||g.domainLookupEnd<g.domainLookupStart||g.domComplete<g.domLoading||g.fetchStart<g.navigationStart||g.loadEventEnd<g.loadEventStart||g.loadEventEnd<g.navigationStart||g.responseEnd<g.responseStart||
g.responseStart<g.requestStart||d.q("//"+b.join("/"))}Math.random()<h.remoteProbingSampleRate&&y(d,h)}function x(d,h){var g=20;return function(){0<g--?0<d.g.performance.timing.loadEventEnd&&(d.g.clearInterval(d.U),w(d,h)):(d.g.clearInterval(d.U),Math.random()<h.remoteProbingSampleRate&&y(d,h))}}
function p(d){function h(d,b){for(var e="",h=0;h<d.length;h++)e=b(e,d[h],h);return e}switch(typeof d){case "string":return'"'+(""+d).replace(/\"/g,'\\"')+'"';case "number":return isNaN(d)?"null":d;case "boolean":return d?"true":"false";case "undefined":return"null";default:return null===d?"null":""+d!==d&&"[object Array]"==Object.prototype.toString.call(d)?"["+h(d,function(d,b){return d+","+p(b)}).substring(1)+"]":"{"+h(function(d){var b=[],e;for(e in d)b.push(e);return b}(d),function(g,b){void 0!==
d[b]&&"function"!==typeof d[b]&&(g+=","+p(b)+":"+p(d[b]));return g}).substring(1)+"}"}};m.prototype.T="j1";function r(d){var h=new XMLHttpRequest;d.c=d.c||{};if(h)try{h.open("GET",d.a,!0),"b"in d&&(h.onreadystatechange=function(){200===this.status&&4===this.readyState&&d.b.call(this)}),d.d&&(h.timeout=d.d),h.send()}catch(g){}}
function t(d,h){return function(){if(this.responseText){var g=/<requestSignature>([\w@]+)</.exec(this.responseText);g&&2===g.length&&(h.requestSignature=g[1],h.requestSignatureTimestamp=(new Date).getTime(),h.notify("init"),h.sendPLT&&Math.random()<h.pltSampleRate?w(d,h):Math.random()<h.remoteProbingSampleRate&&y(d,h))}}}m.prototype.q=function(d){r({a:d})};m.prototype.send_report=m.prototype.q;
function y(d,h){var g,b;g=[];var e="",k=h.deviceCaps.call(h),l=Object.keys(k);for(b=l.length;b--;)g.push(l[b]+"="+k[l[b]]);if(window.location&&window.location.search)for((b=/radar-location=\w+-\w+-\w+/.exec(window.location.search))&&g.push(b[0]),k=window.location.search.slice(1).split("&"),b=k.length;b--;)l=k[b].split("="),2===l.length&&("radar-geo"===l[0]?(l=l[1].split("-"),g.push("country="+l[0]),g.push("asn="+l[1])):"radar-provider-count"===l[0]&&g.push("providerCount="+l[1]));0<g.length&&(e="?"+
g.join("&"));g=[h.domains.code,h.zoneId,h.customerId,"radar",h.buildTimestamp,d.I(20),"providers.json"];g="//"+g.join("/")+e;r({a:g,b:function(a){return function(){var b;try{b=JSON.parse(this.responseText)}catch(d){return}a.za(b,h)}}(d)})}m.prototype.sa=function(d,h){if("function"===typeof h){var g;var b;(b=this.g.crypto||this.g.msCrypto)&&b.getRandomValues?(g=new Uint32Array(1),b.getRandomValues(g),g=g[0]):g=Math.floor(1E9*Math.random());r({a:this.$(d,g),b:h})}};m.prototype.doInitWithCallback=m.prototype.sa;window.cedexis.main=window.cedexis.main||new m({w:window,d:document,samplerId:"j1"});var z,A,B;if(window.cedexis.requestors)for(z=Object.keys(window.cedexis.requestors),A=z.length;A--;)B=window.cedexis.requestors[z[A]],B.transactionId&&!B.runCalledAt&&window.cedexis.main.run(B);}(window,document));