/**
 * © 2015 Cedexis Inc.
 * Radar JavaScript client
 * Application Version: 0.1.230
 * Build Timestamp: 1444163736
 */
(function(window,document){'use strict';var g={"true":!0};window.cedexis=window.cedexis||{};window.cedexis.radar=window.cedexis.radar||{};window.radar=window.radar||{};window.cdx=window.cdx||{};
function h(a){this.window=a.window;this.document=a.document;this.zoneId=a.B;this.customerId=a.j;this.createdAt=(new Date).getTime();this.domains={code:a.s,init:a.m,report:a.v};this.runCalledAt=0;this.sendPLT=a.w in g;this.startDelay=a.A;this.masterSampleRate=a.o;this.pltSampleRate=a.q;this.remoteProbingSampleRate=a.u;this.sendParentMessages=!1;k(this,"startDelay","radar-start-delay");k(this,"masterSampleRate","radar-master-sample-rate");k(this,"pltSampleRate","radar-plt-sample-rate");k(this,"remoteProbingSampleRate",
"radar-remote-probing-sample-rate");k(this,"sendParentMessages","radar-send-parent-messages");this.includePartnerTags=a.k in g;this.buildTimestamp=a.i;this.d=[];this.api={requestor:this,zoneId:this.zoneId,customerId:this.customerId,extend:function(a,c){this[a]=c}};this.c=function(a){return/radar-no-ajax/i.test(a.location.search)?!1:a.XMLHttpRequest&&"undefined"!==typeof(new a.XMLHttpRequest).withCredentials?!0:!1}(a.window);this.plugins=[];this.f=null}h.prototype.browserHasCorsSupport=function(){return this.c};
function k(a,b,c){if(1<a.window.location.search.length)for(var d=a.window.location.search.slice(1).split("&"),f=d.length;f--;){var e=d[f].split("=");if(2===e.length&&c===e[0])if(e=parseInt(e[1],10),isNaN(e))a.log("Warning: "+c+" should be set to a number");else{switch(b){case "masterSampleRate":case "remoteProbingSampleRate":case "pltSampleRate":e/=100;break;case "startDelay":e*=1E3;break;case "sendParentMessages":e=0<e?!0:!1}a[b]=e;a.log(b+" set to "+e)}}}
h.prototype.log=function(a){(this.window.console||{log:function(){}}).log(a)};
h.prototype.h=function(){return{a:this.c?"1":"0",b:function(a){a=a.createElement("script");return a.addEventListener?"2":a.readyState?"1":"0"}(this.document),l:"function"!==typeof Object.keys?"1":"0",n:function(a,b){if(/msie/i.test(a.navigator.userAgent))if(void 0!==b.documentMode){if(9>b.documentMode)return"0"}else if("BackCompat"===b.compatMode)return"0";return void 0===a.performance?"0":"1"}(this.window,this.document),p:function(a){return"function"===typeof a.postMessage&&"function"===typeof a.addEventListener?
"1":"0"}(this.window),r:function(a){var b;if(b=a.performance&&"function"===typeof a.performance.getEntriesByType)a=/msie (\d+)/i.exec(a.navigator.userAgent),b=!(a&&10>=parseInt(a[1],10));return b?"1":"0"}(this.window),t:/(iphone|ipad|android|iemobile|opera mini|ucbrowser|blackberry)/i.test(this.window.navigator.userAgent)?"0":"1"}};h.prototype.deviceCaps=h.prototype.h;
function l(){var a=m.window.navigator.userAgent;if("Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36"===a)return!0;for(var b=[/opera mini/i,/skyfire/i,/teashark/i,/uzard/i,/puffin/i,/yabrowser/i],c=b.length;c--;)if(b[c].test(a))return!0;return!1}
function n(){var a={G:/keynote/i,H:/ KTXN /,D:/gomez/i,C:/catchpoint/i,I:/pingdom/i,F:/ip-label/,J:/witbe-/i},b,c,d;b=window.cedexis.radar.allowed_monitoring_agents||[];c=function(a){var c,d;for(c=0;c<b.length;c+=1)if(d=b[c].toLowerCase(),d===a)return!0;return!1};for(d in a)if(a.hasOwnProperty(d)&&a[d].test(window.navigator.userAgent)&&!c(d))return!0;return!1}
h.prototype.e=function(a,b){for(var c=this.window.cedexis.main,d=this.window.navigator,f=a+":"+c.y64enc(p(b)),e=[this.domains.report,"n1"],x=22;x--;)e.push(0);if("function"===typeof d.sendBeacon&&this.requestSignature&&this.requestSignatureTimestamp&&12E4>(new Date).getTime()-this.requestSignatureTimestamp)e.push(this.requestSignature),e.push(f),e.push(0),d.sendBeacon("//"+e.join("/"));else if(c&&"doInitWithCallback"in c&&this.c){var y=this;c.doInitWithCallback(this,function(){return function(){if(this.responseText){var a=
/<requestSignature>([\w@]+)</.exec(this.responseText);a&&a[1]&&(e.push(a[1]),e.push(f),e.push(0),y.window.cedexis.main.send_report("//"+e.join("/")))}}}())}};h.prototype.plt_ex=h.prototype.e;h.prototype.impact=function(a){this.window.cedexis&&this.window.cedexis.main?this.e("impact_kpi",a):this.d.push(a)};h.prototype.afterRun=function(){for(var a=10;a--&&0<this.d.length;)this.e("impact_kpi",this.d.shift())};
h.prototype.g=function(a){if(this.window.XMLHttpRequest){var b=new this.window.XMLHttpRequest;if("undefined"!==typeof b.withCredentials){var c=a.method.toUpperCase();try{b.open(c,a.url,!0);var d=a.headers||{},f;for(f in d)d.hasOwnProperty(f)&&b.setRequestHeader(f,d[f]);"POST"===c?b.send(a.data):b.send()}catch(e){}}}};h.prototype.ajax=h.prototype.g;
h.prototype.f1=function(a){this.requestSignature&&this.g({method:"get",url:["//rpt.cedexis.com/f1",this.requestSignature,a.providerOwnerZoneId,a.providerOwnerCustomerId,a.providerId,a.probeTypeId,a.resultCode,a.measurement].join("/")})};h.prototype.addPlugin=function(a){for(var b=0;b<this.plugins.length;b++)if(a===this.plugins[b])return;this.plugins.push(a)};h.prototype.notify=function(a){for(var b=0;b<this.plugins.length;b++){var c=this.plugins[b];"function"===typeof c.notify&&c.notify(a)}};
h.prototype.setImpactObject=function(a){this.f=a};h.prototype.getImpactObject=function(){return this.f};
function p(a){function b(a,b){for(var f="",e=0;e<a.length;e++)f=b(f,a[e],e);return f}switch(typeof a){case "string":return'"'+(""+a).replace(/\"/g,'\\"')+'"';case "number":return isNaN(a)?"null":a;case "boolean":return a?"true":"false";case "undefined":return"null";default:return null===a?"null":""+a!==a&&"[object Array]"==Object.prototype.toString.call(a)?"["+b(a,function(a,b){return a+","+p(b)}).substring(1)+"]":"{"+b(function(a){var b=[],f;for(f in a)b.push(f);return b}(a),function(b,d){void 0!==
a[d]&&"function"!==typeof a[d]&&(b+=","+p(d)+":"+p(a[d]));return b}).substring(1)+"}"}};var m=new h({window:window,document:document,B:"1",j:"18573",s:"radar.cedexis.com",m:"cedexis-radar.net",v:"rpt.cedexis.com",w:"true",A:parseInt("5000",10),o:parseFloat("1"),q:parseFloat("1"),u:parseFloat("1"),k:"true",i:parseInt("1444163736",10)});
if(Math.random()<m.masterSampleRate){var q=window.cedexis;q.requestors=q.requestors||{};q.requestors["1;18573"]=m;var r;if(r=!l()){var t;(t=!n())||(t=/radar-allow-monitors=1/.test(m.window.location.search));r=t}if(r){var u=m;"function"===typeof u.window.cedexisInit&&u.window.cedexisInit(u.api);var v=/cedexisInit(\d+)/,w;for(w in u.window){var z=v.exec(w);if(z&&u.customerId==z[1]&&"function"===typeof u.window[z[0]])u.window[w](u.api)}setTimeout(function(){var a=
m,b;var c;(c=a.window.crypto||a.window.msCrypto)&&c.getRandomValues?(b=new Uint32Array(1),c.getRandomValues(b),b=b[0]):b=0;a.transactionId=b||Math.floor(1E9*Math.random());b=a.h();var d=c="",f;for(f in b)b.hasOwnProperty(f)&&(d+=c+f+"="+b[f],c="&");f="//"+a.domains.code+"/"+a.buildTimestamp+"/radar/main.js?"+d;a:{if(0<a.window.location.search.length){b=a.window.location.search.slice(1).split("&");c=[];for(d=b.length;d--;)"providers=all"===b[d]&&c.push(b[d]);c=c.join("&");if(0<c.length){b=
"&"+c;break a}}b=""}f=f+b;b=a.document.getElementById("cdx");b||(b=a.document.createElement("div"),b.id="cdx",a.document.body.appendChild(b));a=a.document.createElement("script");a.type="text/javascript";a.async=!0;a.src=f;b.appendChild(a)},m.startDelay)}};}(window,document));